[phases.setup]
nixPkgs = ["php83", "php83Extensions.pgsql", "php83Extensions.pdo_pgsql"]

[phases.install]
cmds = ["mkdir -p /etc/php83", "echo 'extension=pgsql' >> /etc/php83/php.ini", "echo 'extension=pdo_pgsql' >> /etc/php83/php.ini"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-3000} router.php"
