-- Seed: Admin account (username: admin, password: admin)
-- password_hash generated by PHP: password_hash('admin', PASSWORD_BCRYPT)
INSERT INTO users (nama, email, username, password_hash, role, asal_sekolah)
VALUES ('Admin Utama', 'admin@smartlomba.local', 'admin', '$2y$12$kidmTocnwqJumFXJcHSPn.TLse1/bsUYjFyr/GK3zs.DdleROfZlS', 'admin', 'SmartLomba')
ON CONFLICT (username) DO NOTHING;

-- Seed: Sample lomba
INSERT INTO lomba (nama_lomba, kode_lomba, deskripsi, tanggal_pelaksanaan, maksimal_peserta, pelaksana) VALUES
('Olimpiade Matematika', 'OLM-MAT-2025', 'Kompetisi matematika tingkat nasional untuk siswa SD, SMP, dan SMA/SMK.', '2025-10-14', 100, 'Kementerian Pendidikan'),
('Olimpiade IPA', 'OLM-IPA-2025', 'Kompetisi ilmu pengetahuan alam tingkat nasional.', '2025-10-15', 80, 'Kementerian Pendidikan'),
('Lomba Bahasa Indonesia', 'LBI-2025', 'Lomba kemampuan bahasa Indonesia, meliputi menulis dan pidato.', '2025-10-16', 60, 'Balai Bahasa'),
('Lomba Bahasa Inggris', 'LBE-2025', 'Kompetisi bahasa Inggris: speech, debate, dan essay.', '2025-10-17', 60, 'British Council Indonesia')
ON CONFLICT (kode_lomba) DO NOTHING;
